# Generated by Django 4.2.29 on 2026-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_soil_moisture', models.FloatField(help_text='Current volumetric water content (m³/m³)')),
                ('stress_threshold', models.FloatField(help_text='Management Allowable Depletion threshold — below this, crop is under water stress')),
                ('ideal_soil_moisture', models.FloatField(help_text='Target soil moisture at field capacity — irrigation refills toward this value')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
